### ISSUE TITLE
tensorflow

### ISSUE THREAD

**Issue by PIPIPIG233666** [PIPIPIG233666/gentoo_pppig#7]
tensorboard

**Comment by PIPIPIG233666** [comment]
bazel still fails bc of gcc13 smh

**Comment by PIPIPIG233666** [comment]
bazel 7.0.0 pre rs has the fixes
tensorboard now builds
tensorflow next

**Comment by PIPIPIG233666** [comment]
so apparently even official tensorflow struggles to build w/ rocm...

**Comment by PIPIPIG233666** [comment]
```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalStateException: Unexpected inconsistency: PACKAGE_LOOKUP:@rules_proto//proto, [REPOSITORY_DIRECTORY:@rules_proto], ALREADY_DECLARED_CHILD_MISSING
        at com.google.devtools.build.skyframe.GraphInconsistencyReceiver.lambda$static$0(GraphInconsistencyReceiver.java:37)
        at com.google.devtools.build.skyframe.SkyFunctionEnvironment.batchPrefetch(SkyFunctionEnvironment.java:263)
        at com.google.devtools.build.skyframe.SkyFunctionEnvironment.<init>(SkyFunctionEnvironment.java:215)
        at com.google.devtools.build.skyframe.SkyFunctionEnvironment.create(SkyFunctionEnvironment.java:166)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:482)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

ERROR: Could not build Bazel
 * ERROR: dev-util/bazel-7.0.0::pppig failed (compile phase):
 *   Failed compiling bazel
 * 
 * Call stack:
 *     ebuild.sh, line 136:  Called src_compile
 *   environment, line 3011:  Called die
 * The specific snippet of code:
 *       VERBOSE=yes ./compile.sh || die "Failed compiling bazel";
 * 
 * If you need support, post the output of `emerge --info '=dev-util/bazel-7.0.0::pppig'`,
 * the complete build log and the output of `emerge -pqv '=dev-util/bazel-7.0.0::pppig'`.
!!! When you file a bug report, please include the following information:
GENTOO_VM=openjdk-bin-11  CLASSPATH="" JAVA_HOME="/opt/openjdk-bin-11.0.19_p7"
JAVACFLAGS="-source 11 -target 11" COMPILER="
```

**Comment by PIPIPIG233666** [comment]
gcc is the way for bazel and java
